#Sample docker compose file for the dockjob image.
# this shows how to run dockjob using kong to make it https
#  dock job itself isn't exposed, instead kong is exposed and passes requests to dockjob
# execute it with the command "docker stack deploy --compose-file=docker-compose-https.yml dockjob-https"
#
#note: it is recomended you change :latest to a spercific version number

version: "3.1"

secrets:
  webservices_cert:
    external: true
  webservices_key:
    external: true

services:
  kong-database:
    image: postgres:9.4
    deploy:
      restart_policy:
        condition: any
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:0.12.0
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up
    deploy:
      restart_policy:
        condition: on-failure

  kong:
    #tried changing to kong:0.12.0-alpine but didn't work as health check needs curl
    image: kong:0.12.0
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
     - webservices_cert
     - webservices_key
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_SSL_CERT=/run/secrets/webservices_cert
      - KONG_SSL_CERT_KEY=/run/secrets/webservices_key
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 443:8443
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10

  dockjob:
    image: metcarob/dockjob:latest
    environment:
      - APIAPP_APIURL=https://cat-sdts.metcarob-home.com:443/dockjobapi
    deploy:
      restart_policy:
        condition: any

  #Add API's to kong to forward requests to dockjob
  kong-addapis-dockjob:
    image: byrnedo/alpine-curl
    deploy:
      restart_policy:
        condition: on-failure
        delay: 6s
    entrypoint: "/bin/sh"
    command:    "-c \" \
                   (curl -i -X POST \
                     --url http://kong:8001/apis/ \
                     --data 'name=dockjobapi' \
                     --data 'uris=/dockjobapi' \
                     --data 'upstream_url=http://dockjob:80/dockjobapi' \
                     --data 'https_only=true') && \
                   (curl -i -X POST \
                     --url http://kong:8001/apis/ \
                     --data 'name=dockjob' \
                     --data 'uris=/dockjob' \
                     --data 'upstream_url=http://dockjob:80/dockjobfrontend' \
                     --data 'https_only=true') \
               \""

