#Sample docker compose file for the dockjob image.
# this shows how to run it stand-alone
# execute it with the command "docker stack deploy --compose-file=docker-compose-standalone.yml dockjob-standalone"
#
#note: it is recomended you change :latest to a spercific version number

version: "3.1"

services:
  dockjob:
    image: metcarob/dockjob:latest
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: any


