#Sample docker compose file for the dockjob image.
# this shows how to run it stand-alone
# execute it with the command "docker stack deploy --compose-file=docker-compose-standalone.yml dockjob-standalone"
#
#note: it is recommended you change :latest to a specific version number

version: "3.1"

services:
  dockjob:
    image: metcarob/dockjob:latest
    ports:
      - 80:80
    environment:
      - APIAPP_APIURL=http://localhost:80/api
      - APIAPP_APIDOCSURL=http://localhost:80/apidocs/
    deploy:
      restart_policy:
        condition: any


